# Generated by Django 3.0.8 on 2020-07-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20200718_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='username',
            new_name='name',
        ),
    ]
